import * as fs from 'fs'
import * as path from 'path'

/**
 * API 代码生成器
 */
export class ApiGenerator {
  private pathsByTag: Record<string, any[]> = {}

  constructor(pathsByTag: Record<string, any[]>) {
    this.pathsByTag = pathsByTag
  }

  /**
   * 生成函数名
   */
  private generateFunctionName(method: string, path: string): string {
    const parts = path.split('/').filter(p => p && !p.startsWith('{'))
    const methodMap: Record<string, string> = {
      GET: 'get',
      POST: 'create',
      PUT: 'update',
      DELETE: 'delete',
      PATCH: 'patch',
    }

    const prefix = methodMap[method] || method.toLowerCase()
    const suffix = parts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('')

    return `${prefix}${suffix}`
  }

  /**
   * 提取路径参数
   */
  private extractPathParams(path: string): string[] {
    const matches = path.match(/\{([^}]+)\}/g)
    return matches ? matches.map(m => m.slice(1, -1)) : []
  }

  /**
   * 生成参数类型
   */
  private generateParamsType(operation: any, pathParams: string[]): string {
    const params: string[] = []

    // 路径参数
    pathParams.forEach((param) => {
      params.push(`  ${param}: string | number`)
    })

    // 查询参数
    const queryParams = operation.parameters?.filter((p: any) => p.in === 'query') || []
    queryParams.forEach((param: any) => {
      const required = param.required ? '' : '?'
      params.push(`  ${param.name}${required}: ${this.mapType(param.type || param.schema?.type)}`)
    })

    return params.length > 0 ? `{\n${params.join('\n')}\n}` : 'never'
  }

  /**
   * 映射类型
   */
  private mapType(type: string): string {
    const typeMap: Record<string, string> = {
      string: 'string',
      number: 'number',
      integer: 'number',
      boolean: 'boolean',
      array: 'any[]',
      object: 'any',
    }
    return typeMap[type] || 'any'
  }

  /**
   * 生成单个 API 函数
   */
  private generateApiFunction(item: any): string {
    const { path, method, operation } = item
    const functionName = this.generateFunctionName(method, path)
    const pathParams = this.extractPathParams(path)
    const hasBody = ['POST', 'PUT', 'PATCH'].includes(method)
    const paramsType = this.generateParamsType(operation, pathParams)
    const summary = operation.summary || operation.description || ''

    let params = ''
    let urlPath = path
    let requestOptions = ''

    // 处理参数
    if (pathParams.length > 0 || paramsType !== 'never') {
      params += 'params: ' + paramsType
    }

    if (hasBody) {
      params += params ? ', data?: any' : 'data?: any'
    }

    // 处理路径参数替换
    pathParams.forEach((param) => {
      urlPath = urlPath.replace(`{${param}}`, `\${params.${param}}`)
    })

    // 处理请求选项
    if (hasBody) {
      requestOptions = ', data'
    }
    else if (paramsType !== 'never') {
      requestOptions = ', params'
    }

    const comment = summary ? `/**\n * ${summary}\n */\n` : ''

    return `${comment}export const ${functionName} = (${params}) => {
  return request.${method.toLowerCase()}<any>(\`${urlPath}\`${requestOptions})
}\n`
  }

  /**
   * 生成 API 模块
   */
  generateApiModule(tag: string, apis: any[]): string {
    let output = '/**\n * Auto generated by swagger-parser\n * Do not edit manually\n */\n\n'
    output += 'import request from \'@/utils/request\'\n\n'

    apis.forEach((api) => {
      output += this.generateApiFunction(api)
      output += '\n'
    })

    return output
  }

  /**
   * 生成所有 API 模块
   */
  generateAllModules(outputDir: string): void {
    const indexExports: string[] = []

    for (const [tag, apis] of Object.entries(this.pathsByTag)) {
      const fileName = tag.toLowerCase().replace(/\s+/g, '-')
      const filePath = path.join(outputDir, `${fileName}.ts`)
      const content = this.generateApiModule(tag, apis)

      const dir = path.dirname(filePath)
      if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true })
      }

      fs.writeFileSync(filePath, content, 'utf-8')
      console.log(`✅ API 模块已生成: ${filePath}`)

      indexExports.push(`export * from './${fileName}'`)
    }

    // 生成 index.ts
    const indexPath = path.join(outputDir, 'index.ts')
    const indexContent = indexExports.join('\n') + '\n'
    fs.writeFileSync(indexPath, indexContent, 'utf-8')
    console.log(`✅ API 索引文件已生成: ${indexPath}`)
  }
}
