import * as fs from 'fs'
import * as path from 'path'

/**
 * TypeScript 类型生成器
 */
export class TypeGenerator {
  private definitions: Record<string, any> = {}

  constructor(definitions: Record<string, any>) {
    this.definitions = definitions
  }

  /**
   * 映射 Swagger 类型到 TypeScript 类型
   */
  private mapType(schema: any): string {
    if (!schema)
      return 'any'

    if (schema.$ref) {
      const refName = schema.$ref.split('/').pop()
      return refName || 'any'
    }

    if (schema.type === 'array') {
      return `${this.mapType(schema.items)}[]`
    }

    if (schema.type === 'object') {
      if (schema.properties) {
        return this.generateInterface(schema)
      }
      return 'Record<string, any>'
    }

    const typeMap: Record<string, string> = {
      string: 'string',
      number: 'number',
      integer: 'number',
      boolean: 'boolean',
      file: 'File',
    }

    return typeMap[schema.type] || 'any'
  }

  /**
   * 生成接口
   */
  private generateInterface(schema: any, indent = ''): string {
    if (!schema.properties)
      return '{}'

    const properties = Object.keys(schema.properties).map((key) => {
      const prop = schema.properties[key]
      const required = schema.required?.includes(key) ? '' : '?'
      const type = this.mapType(prop)
      const description = prop.description ? `\n${indent}  /** ${prop.description} */` : ''
      return `${description}\n${indent}  ${key}${required}: ${type}`
    })

    return `{\n${properties.join('\n')}\n${indent}}`
  }

  /**
   * 生成枚举
   */
  private generateEnum(name: string, values: any[]): string {
    const enumValues = values.map(v => `  ${v} = '${v}',`).join('\n')
    return `export enum ${name} {\n${enumValues}\n}\n`
  }

  /**
   * 生成类型定义
   */
  generateTypes(): string {
    let output = '/**\n * Auto generated by swagger-parser\n * Do not edit manually\n */\n\n'

    for (const [name, schema] of Object.entries(this.definitions)) {
      const description = schema.description ? `/**\n * ${schema.description}\n */\n` : ''

      // 处理枚举
      if (schema.enum) {
        output += description
        output += this.generateEnum(name, schema.enum)
        output += '\n'
        continue
      }

      // 处理接口
      output += description
      output += `export interface ${name} ${this.generateInterface(schema)}\n\n`
    }

    return output
  }

  /**
   * 保存类型文件
   */
  saveToFile(outputPath: string): void {
    const content = this.generateTypes()
    const dir = path.dirname(outputPath)

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    fs.writeFileSync(outputPath, content, 'utf-8')
    console.log(`✅ 类型文件已生成: ${outputPath}`)
  }
}
